// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkKPxzhU4O7WAE5X2ELle86kTgsNXI9Xs',
    appId: '1:1059538703579:web:be0d836ec8d9654e00e8fe',
    messagingSenderId: '1059538703579',
    projectId: 'books-friend-e1e38',
    authDomain: 'books-friend-e1e38.firebaseapp.com',
    storageBucket: 'books-friend-e1e38.appspot.com',
    measurementId: 'G-K60WK4PW81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsP74k-G0sizRdd_ZzRNGF3oAKJ6FzMY0',
    appId: '1:1059538703579:android:ba7bca7ddc991ea500e8fe',
    messagingSenderId: '1059538703579',
    projectId: 'books-friend-e1e38',
    storageBucket: 'books-friend-e1e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWxY94kRwGPijHeOGPk7gMnwlcfVatmg',
    appId: '1:1059538703579:ios:f65536d1b8cda4a000e8fe',
    messagingSenderId: '1059538703579',
    projectId: 'books-friend-e1e38',
    storageBucket: 'books-friend-e1e38.appspot.com',
    iosClientId:
        '1059538703579-uq3kg55u4c92iapauecivkjc6f7g42rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.books.booksFriend',
  );
}
